name: Code quality

on:
    push:
        branches: [$default-branch]
    pull_request:
        branches: ["*"]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: "Cache node_modules"
              uses: actions/cache@v2
              with:
                  path: ./node_modules
                  key: node-npm-${{ hashFiles('./package-lock.json') }}

            - name: "Node.js dependencies install"
              run: npm install

            - name: "Run main code quality checks"
              run: npm run ci:check

            - name: "Transpile TypeScript code to JavaScript, so we can run the one in the 'src/scripts' folder"
              run: npm run scripts:transpile

            - name: "[scripts] Check galleries' images sizes"
              run: npm run scripts:check-gallery-images-dimensions
