name: Code quality

on:
    push:
        branches: [$default-branch]
    pull_request:
        branches: ["*"]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Cache node_modules
              uses: actions/cache@v2
              with:
                  path: ./node_modules
                  key: node-npm-${{ hashFiles('./package-lock.json') }}

            - run: npm install
            - run: npm run ci:check
